package krys.itemimport;

import java.util.List;

/** Wspólny punkt dostępu do katalogu affixów aplikacji. */
public final class ApplicationAffixRegistry {
    private static final List<AffixDefinition> SEED_DEFINITIONS = List.of(
            new AffixDefinition(
                    "verathiel_weapon_damage_flat",
                    ImportedItemAffixType.WEAPON_DAMAGE_FLAT,
                    "Obrażenia od broni",
                    AffixCategory.OFFENSIVE,
                    List.of("obrażeń od broni", "obrażen od broni", "obrażen od broni", "obrazen od broni"),
                    AffixValueUnit.FLAT,
                    94.0d,
                    94.0d,
                    157.0d,
                    null,
                    null,
                    AffixRuntimeStatus.DESCRIPTIVE_ONLY,
                    true,
                    true
            ),
            new AffixDefinition(
                    "life_on_kill",
                    ImportedItemAffixType.LIFE_ON_KILL,
                    "Zdrowie za zabicie",
                    AffixCategory.DEFENSIVE,
                    List.of("zdrowia za zabicie", "life on kill"),
                    AffixValueUnit.FLAT,
                    null,
                    300.0d,
                    300.0d,
                    null,
                    null,
                    AffixRuntimeStatus.DESCRIPTIVE_ONLY,
                    true,
                    true
            ),
            new AffixDefinition(
                    "damage_over_time_multiplier",
                    ImportedItemAffixType.DAMAGE_OVER_TIME_MULTIPLIER,
                    "Mnożnik obrażeń z upływem czasu",
                    AffixCategory.OFFENSIVE,
                    List.of("obrażeń z upływem czasu", "obrazen z uplywem czasu", "damage over time", "dot multiplier"),
                    AffixValueUnit.PERCENT,
                    null,
                    15.0d,
                    30.0d,
                    null,
                    null,
                    AffixRuntimeStatus.DESCRIPTIVE_ONLY,
                    true,
                    true
            ),
            new AffixDefinition(
                    "verathiel_maximum_life",
                    ImportedItemAffixType.MAXIMUM_LIFE,
                    "Maksymalne zdrowie",
                    AffixCategory.DEFENSIVE,
                    List.of("maksymalnego zdrowia", "maksymalne zdrowie", "maximum life"),
                    AffixValueUnit.FLAT,
                    2141.0d,
                    1831.0d,
                    2200.0d,
                    null,
                    null,
                    AffixRuntimeStatus.DESCRIPTIVE_ONLY,
                    true,
                    true
            ),
            new AffixDefinition(
                    "verathiel_life_on_hit",
                    ImportedItemAffixType.LIFE_ON_HIT,
                    "Zdrowie przy trafieniu",
                    AffixCategory.DEFENSIVE,
                    List.of("pkt. zdrowia przy trafieniu", "zdrowia przy trafieniu", "life on hit"),
                    AffixValueUnit.POINTS,
                    545.0d,
                    526.0d,
                    632.0d,
                    null,
                    null,
                    AffixRuntimeStatus.DESCRIPTIVE_ONLY,
                    true,
                    true
            ),
            new AffixDefinition(
                    "verathiel_lucky_hit_primary_resource",
                    ImportedItemAffixType.LUCKY_HIT_PRIMARY_RESOURCE,
                    "Szczęśliwy traf: zasób podstawowy",
                    "Szczęśliwy traf: maksymalnie 15% szans na odzyskanie +X podstawowego zasobu",
                    AffixCategory.RESOURCE,
                    List.of("Szczęśliwy traf", "Szczesliwy traf", "maksymalnie 15% szans", "odzyskanie +3 podstawowego zasobu"),
                    AffixValueUnit.TEXT,
                    3.0d,
                    3.0d,
                    4.0d,
                    15.0d,
                    3.0d,
                    AffixRuntimeStatus.DESCRIPTIVE_ONLY,
                    true,
                    true
            ),
            new AffixDefinition(
                    "strength",
                    ImportedItemAffixType.STRENGTH,
                    "Siła",
                    AffixCategory.ATTRIBUTE,
                    List.of("siły", "sily", "strength"),
                    AffixValueUnit.FLAT,
                    null,
                    null,
                    null,
                    null,
                    null,
                    AffixRuntimeStatus.DESCRIPTIVE_ONLY,
                    true,
                    true
            ),
            new AffixDefinition(
                    "intelligence",
                    ImportedItemAffixType.INTELLIGENCE,
                    "Inteligencja",
                    AffixCategory.ATTRIBUTE,
                    List.of("inteligencji", "intelligence"),
                    AffixValueUnit.FLAT,
                    null,
                    null,
                    null,
                    null,
                    null,
                    AffixRuntimeStatus.DESCRIPTIVE_ONLY,
                    true,
                    true
            ),
            new AffixDefinition(
                    "thorns",
                    ImportedItemAffixType.THORNS,
                    "Ciernie",
                    AffixCategory.DEFENSIVE,
                    List.of("cierni", "thorns"),
                    AffixValueUnit.POINTS,
                    null,
                    null,
                    null,
                    null,
                    null,
                    AffixRuntimeStatus.DESCRIPTIVE_ONLY,
                    true,
                    true
            ),
            new AffixDefinition(
                    "all_resistance",
                    ImportedItemAffixType.ALL_RESISTANCE,
                    "Odporność na wszystkie żywioły",
                    AffixCategory.DEFENSIVE,
                    List.of("do odporności na wszystkie żywioły", "odporności na wszystkie żywioły", "do odpornosci na wszystkie zywioly", "odpornosc na wszystkie zywioly", "resistance to all elements"),
                    AffixValueUnit.FLAT,
                    null,
                    null,
                    null,
                    null,
                    null,
                    AffixRuntimeStatus.DESCRIPTIVE_ONLY,
                    true,
                    true
            ),
            new AffixDefinition(
                    "fire_resistance",
                    ImportedItemAffixType.FIRE_RESISTANCE,
                    "Odporność na Ogień",
                    AffixCategory.DEFENSIVE,
                    List.of("do odporności na: ogień", "do odporności na ogień", "odporności na: ogień", "odporności na ogień", "do odpornosci na ogien", "odpornosc na ogien", "fire resistance"),
                    AffixValueUnit.FLAT,
                    null,
                    null,
                    null,
                    null,
                    null,
                    AffixRuntimeStatus.DESCRIPTIVE_ONLY,
                    true,
                    true
            ),
            new AffixDefinition(
                    "damage_reduction",
                    ImportedItemAffixType.DAMAGE_REDUCTION,
                    "Redukcja obrażeń",
                    AffixCategory.DEFENSIVE,
                    List.of("redukcji obrażeń", "redukcja obrażeń", "damage reduction"),
                    AffixValueUnit.PERCENT,
                    null,
                    11.0d,
                    15.0d,
                    null,
                    null,
                    AffixRuntimeStatus.DESCRIPTIVE_ONLY,
                    true,
                    true
            ),
            new AffixDefinition(
                    "block_chance",
                    ImportedItemAffixType.BLOCK_CHANCE,
                    "Szansa na blok",
                    AffixCategory.DEFENSIVE,
                    List.of("szansy na blok", "szansa na blok", "block chance"),
                    AffixValueUnit.PERCENT,
                    null,
                    null,
                    null,
                    null,
                    null,
                    AffixRuntimeStatus.DESCRIPTIVE_ONLY,
                    true,
                    true
            ),
            new AffixDefinition(
                    "retribution_chance",
                    ImportedItemAffixType.RETRIBUTION_CHANCE,
                    "Szansa retribution",
                    AffixCategory.UTILITY,
                    List.of("retribution", "odwet"),
                    AffixValueUnit.PERCENT,
                    null,
                    null,
                    null,
                    null,
                    null,
                    AffixRuntimeStatus.DESCRIPTIVE_ONLY,
                    true,
                    true
            ),
            new AffixDefinition(
                    "lucky_hit_chance",
                    ImportedItemAffixType.LUCKY_HIT_CHANCE,
                    "Szansa na szczęśliwy traf",
                    AffixCategory.UTILITY,
                    List.of("szansy na szczęśliwy traf", "szansa na szczęśliwy traf",
                            "szansy na szczesliwy traf", "szansa na szczesliwy traf",
                            "szansy szczesliwy traf", "szansy szczesnwy traf",
                            "szansy traf", "szansy wy traf",
                            "lucky hit chance"),
                    AffixValueUnit.PERCENT,
                    null,
                    null,
                    null,
                    null,
                    null,
                    AffixRuntimeStatus.DESCRIPTIVE_ONLY,
                    true,
                    true
            ),
            new AffixDefinition(
                    "critical_strike_chance",
                    ImportedItemAffixType.CRITICAL_STRIKE_CHANCE,
                    "Szansa na trafienie krytyczne",
                    AffixCategory.OFFENSIVE,
                    List.of("szansy na trafienie krytyczne", "szansa na trafienie krytyczne", "critical strike chance"),
                    AffixValueUnit.PERCENT,
                    null,
                    null,
                    null,
                    null,
                    null,
                    AffixRuntimeStatus.DESCRIPTIVE_ONLY,
                    true,
                    true
            ),
            new AffixDefinition(
                    "cooldown_reduction",
                    ImportedItemAffixType.COOLDOWN_REDUCTION,
                    "Redukcja czasu odnowienia",
                    AffixCategory.UTILITY,
                    List.of("redukcji czasu odnowienia", "cooldown"),
                    AffixValueUnit.PERCENT,
                    null,
                    null,
                    null,
                    null,
                    null,
                    AffixRuntimeStatus.DESCRIPTIVE_ONLY,
                    true,
                    true
            ),
            new AffixDefinition(
                    "movement_speed",
                    ImportedItemAffixType.MOVEMENT_SPEED,
                    "Szybkość ruchu",
                    AffixCategory.UTILITY,
                    List.of("szybkości ruchu", "szybkosci ruchu", "movement speed"),
                    AffixValueUnit.PERCENT,
                    null,
                    null,
                    null,
                    null,
                    null,
                    AffixRuntimeStatus.DESCRIPTIVE_ONLY,
                    true,
                    true
            ),
            new AffixDefinition(
                    "dodge_chance",
                    ImportedItemAffixType.DODGE_CHANCE,
                    "Unik",
                    AffixCategory.DEFENSIVE,
                    List.of("uniku", "dodge"),
                    AffixValueUnit.PERCENT,
                    null,
                    null,
                    null,
                    null,
                    null,
                    AffixRuntimeStatus.DESCRIPTIVE_ONLY,
                    true,
                    true
            ),
            new AffixDefinition(
                    "core_skill_ranks",
                    ImportedItemAffixType.CORE_SKILL_RANKS,
                    "Rangi umiejętności: Główne",
                    AffixCategory.UTILITY,
                    List.of("do umiejętności: główne", "do umiejętności główne",
                            "do umiejetnosci: glowne", "do umiejetnosci glowne",
                            "umiejętności: główne", "umiejetnosci glowne",
                            "core skill ranks", "core skills"),
                    AffixValueUnit.FLAT,
                    null,
                    null,
                    null,
                    null,
                    null,
                    AffixRuntimeStatus.DESCRIPTIVE_ONLY,
                    true,
                    true
            )
    );

    private static final AffixRegistry INSTANCE = new AffixRegistry(SEED_DEFINITIONS);

    private ApplicationAffixRegistry() {
    }

    public static AffixRegistry get() {
        return INSTANCE;
    }

    static List<AffixDefinition> seedDefinitions() {
        return SEED_DEFINITIONS;
    }
}
